---
title: "flex detail"
subtitle: ""
author: ""
output:
  xaringan::moon_reader:
    seal: FALSE
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:9
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---



```{r, include = F}
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, comment = "", cache = F)
library(flipbookr)
library(tidyverse)
load("current_image.Rdata")
```


```{r, echo = F, eval = TRUE , message = F, warning = F}
xaringanExtra::use_share_again()
```


```{r the_chunk, include = F}
iris[c(1:3, 51:53, 101:104),] %>% 
  flextable(col_keys = 
              c("Species", "col_1", 
               "Sepal.Length", 
               "Petal.Length")) %>% 
  theme_vanilla() %>% 
  autofit() %>% 
  empty_blanks() %>% 
  set_header_labels(
    Sepal.Length = "Sepal length", 
    Sepal.Width = "Sepal width", 
    Petal.Length = "Petal length",
    Petal.Width = "Petal width" )
```

`r chunk_reveal(chunk_name = "the_chunk", break_type = "auto", ...)`



```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 80%}

@media print {
  .has-continuation {
    display: block;
  }
}

code.r.hljs.remark-code{
  position: relative;
  overflow-x: hidden;
}


code.r.hljs.remark-code:hover{
  overflow-x:visible;
  width: 500px;
  border-style: solid;
}
```

