---
title: "flex wide format"
subtitle: ""
author: ""
output:
  xaringan::moon_reader:
    seal: FALSE
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:9
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---



```{r, include = F}
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, comment = "", cache = F)
library(flipbookr)
library(tidyverse)
load("current_image.Rdata")
```


```{r, echo = F, eval = TRUE , message = F, warning = F}
xaringanExtra::use_share_again()
```


```{r the_chunk, include = F}
arranged_table %>% 
  select(-is_sub, -is_grand) %>% 
  flextable() %>% 
  theme_box() %>% 
  merge_v() %>% 
  rotate(j = 1, part = "body", rotation = "btlr") %>% 
  set_header_labels(continent = "",
                    country = "") %>% 
  bg(bg = "aliceblue", part = "all") %>% 
  bg(i = ~ country == "Total", 
     bg = "steelblue3") %>% 
  bg(i = ~ country == "Grand Total", 
     bg = "steelblue3") %>% 
  color (i = ~ country == "Grand Total", 
     color = "grey90") %>% 
  bg(j = "continent", bg = "steelblue3") %>% 
  bold(j = "Total", part = "all") %>% 
  bold(i = ~ str_detect(country, "Total")) %>% 
  font(fontname = "Times") %>% 
  flextable::set_caption("Very good") %>% 
  flextable::add_header(continent = "This is my title") %>% 
  flextable::add_footer(country = "A footnote goes here") %>% 
  merge_h()
  
```

`r chunk_reveal(chunk_name = "the_chunk", break_type = "auto", ...)`



```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 80%}

@media print {
  .has-continuation {
    display: block;
  }
}

code.r.hljs.remark-code{
  position: relative;
  overflow-x: hidden;
}


code.r.hljs.remark-code:hover{
  overflow-x:visible;
  width: 500px;
  border-style: solid;
}
```

