---
title: "flex custom_theme"
subtitle: ""
author: ""
output:
  xaringan::moon_reader:
    seal: FALSE
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:10
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---



```{r, include = F}
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, comment = "", cache = F)
library(flipbookr)
library(tidyverse)
load("current_image.Rdata")
```


```{r, echo = F, eval = FALSE , message = F, warning = F}
xaringanExtra::use_share_again()
```


```{r the_chunk, include = F}
gapminder::gapminder %>% 
  filter(year == 2002) %>% 
  head() %>% 
  flextable() %>% 
  theme_vanilla() %>% 
  color(color = "steelblue", 
        part = "all") %>% 
  bg(bg = "transparent", 
     part = "all") %>% 
  italic(j = 1) %>% 
  bg(bg = "#C90000", 
     part = "header") %>% 
  color(color = "white", 
        part = "header") %>%
  color(~ year > 3.5, ~ year, 
        color = "red") %>% 
  bold(~ year > 3.5, ~ year, 
       bold = TRUE) %>% 
  autofit()
```

`r chunk_reveal(chunk_name = "the_chunk", break_type = "auto", ...)`



```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 90%}

@media print {
  .has-continuation {
    display: block;
  }
}
```

