---
title: "flex theme"
subtitle: ""
author: ""
output:
  xaringan::moon_reader:
    seal: FALSE
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:10
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---



```{r, include = F}
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, comment = "", cache = F)
library(flipbookr)
library(tidyverse)
load("current_image.Rdata")
```


```{r, echo = F, eval = FALSE , message = F, warning = F}
xaringanExtra::use_share_again()
```


```{r the_chunk, include = F}
gapminder::gapminder %>% 
  filter(year == 2002) %>% 
  head() %>% 
  flextable() %>%
  theme_alafoli() %>% #ROTATE
  theme_booktabs() %>% #ROTATE
  theme_box() %>% #ROTATE
  theme_tron() %>% #ROTATE
  theme_tron_legacy() %>% #ROTATE
  theme_vader() %>% #ROTATE
  theme_vanilla() %>% #ROTATE
  theme_zebra() #ROTATE
```

`r chunk_reveal(chunk_name = "the_chunk", break_type = "rotate", ...)`



```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 200%}

@media print {
  .has-continuation {
    display: block;
  }
}
```

