---
title: "gt prep"
subtitle: ""
author: ""
output:
  xaringan::moon_reader:
    seal: FALSE
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:10
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---



```{r, include = F}
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, comment = "", cache = F)
library(flipbookr)
library(tidyverse)
load("current_image.Rdata")
```


```{r, echo = F, eval = FALSE , message = F, warning = F}
xaringanExtra::use_share_again()
```


```{r the_chunk, include = F}
library(gt)
gt::exibble %>% 
  rename(fruit = char) %>%
  rename(team = fctr) %>% 
  rename(weight = num) %>% 
  rename(holiday = date) %>% 
  rename(schedule = time) %>% 
  rename(appointment = datetime) %>% 
  rename(price = currency) %>% 
  rename(id = row) %>% 
  rename(club = group) ->
example

example %>% 
  .[1:5, 1:4] %>% 
  gt() %>%
  fmt_number(columns = vars(weight), 
             decimals = 2) %>%
  fmt_date(columns = vars(holiday), 
           date_style = 1) 
```

`r chunk_reveal(chunk_name = "the_chunk", break_type = "auto", ...)`



```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 90%}

@media print {
  .has-continuation {
    display: block;
  }
}
```

