---
title: "hux large"
subtitle: ""
author: ""
output:
  xaringan::moon_reader:
    seal: FALSE
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:10
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---



```{r, include = F}
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, comment = "", cache = F)
library(flipbookr)
library(tidyverse)
load("current_image.Rdata")
```


```{r, echo = F, eval = TRUE , message = F, warning = F}
xaringanExtra::use_share_again()
```


```{r the_chunk, include = F}
iris %>% 
  group_by(Species) %>% 
  select(Species, Sepal.Length, Sepal.Width, 
             Petal.Length, Petal.Width) %>% 
  slice(1:5) %>% 
  as_hux() %>%
  set_tb_padding(2) %>% 
  set_contents(1, 2:5, c("Length", "Width", "Length", "Width")) %>% 
  insert_row("", "Sepal", "", "Petal", "", after = 0) %>% 
  merge_cells(1, 2:3) %>% 
  merge_cells(1, 4:5) %>% 
  set_align(1, everywhere, "center") %>% 
  set_tb_padding(1, everywhere, 0) %>% 
  set_bold(1, everywhere)
```

`r chunk_reveal(chunk_name = "the_chunk", break_type = "auto", ...)`



```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 120%}

@media print {
  .has-continuation {
    display: block;
  }
}
```

