---
title: "hux reshape"
subtitle: ""
author: ""
output:
  xaringan::moon_reader:
    seal: FALSE
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:10
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---



```{r, include = F}
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, comment = "", cache = F)
library(flipbookr)
library(tidyverse)
load("current_image.Rdata")
```


```{r, echo = F, eval = TRUE , message = F, warning = F}
xaringanExtra::use_share_again()
```


```{r the_chunk, include = F}
matrix(1:16, 4, 4) %>% 
  as_hux() %>% 
  set_background_color(1:2, 1:2, "red") %>% 
  set_background_color(1:2, 3:4, "yellow") %>% 
  set_background_color(3:4, 1:2, "darkgreen") %>% 
  set_background_color(3:4, 3:4, "blue") %>% 
  set_text_color(3:4, 1:4, "white") %>% 
  set_all_borders(brdr(2, "solid", "white")) %>%   
  set_caption("Original table") %>% 
  restack_across(rows = 2) %>% 
  set_caption("Restacked across") %>% 
  restack_down(cols = 2) %>% 
  set_caption("Restacked down")
```

`r chunk_reveal(chunk_name = "the_chunk", break_type = "auto", ...)`



```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 120%}

@media print {
  .has-continuation {
    display: block;
  }
}
```

