---
title: "hux theme1"
subtitle: ""
author: ""
output:
  xaringan::moon_reader:
    seal: FALSE
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:10
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---



```{r, include = F}
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, comment = "", cache = F)
library(flipbookr)
library(tidyverse)
load("current_image.Rdata")
```


```{r, echo = F, eval = TRUE , message = F, warning = F}
xaringanExtra::use_share_again()
```


```{r the_chunk, include = F}
library(huxtable)
gapminder::gapminder %>%
  filter(year == 2002,
         pop > 100000000) %>% 
  arrange(-pop) %>% 
  select(-year) %>% 
  as_hux() %>% 
  set_caption("Most populous Countries, 2002") %>% 
  theme_bright() %>% #ROTATE
  theme_blue() %>% #ROTATE
  theme_article() %>% #ROTATE
  theme_basic() %>% #ROTATE
  theme_compact() %>% #ROTATE
  theme_green() %>% #ROTATE
  theme_grey() %>% #ROTATE
  theme_mondrian() %>% #ROTATE
  theme_orange() %>% #ROTATE
  theme_plain() %>% #ROTATE
  theme_striped() #ROTATE
```

`r chunk_reveal(chunk_name = "the_chunk", break_type = "rotate", ...)`



```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 90%}

@media print {
  .has-continuation {
    display: block;
  }
}
```

