---
title: "hux set"
subtitle: ""
author: ""
output:
  xaringan::moon_reader:
    seal: FALSE
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:10
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---



```{r, include = F}
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, comment = "", cache = F)
library(flipbookr)
library(tidyverse)
load("current_image.Rdata")
```


```{r, echo = F, eval = TRUE , message = F, warning = F}
xaringanExtra::use_share_again()
```


```{r the_chunk, include = F}
jams1 <- jams
# set all padding:
left_padding(jams1) <- 7
right_padding(jams1) <- 20
top_padding(jams1) <- 11
bottom_padding(jams1) <- 12

# set outer padding:
left_padding(jams1)[1:nrow(jams1), 1] <- 3
top_padding(jams1)[1, 1:ncol(jams1)] <- 1
right_padding(jams1)[1:nrow(jams1),
                     ncol(jams1)] <- .3
bottom_padding(jams1)[nrow(jams1),
                      1:ncol(jams1)] <- 0

number_format(jams1) <- 2
bold(jams1)[1, 1:ncol(jams1)] <- TRUE
bottom_border(jams1)[1, 1:ncol(jams1)] <- 0.8
width(jams1) <- 1
caption(jams1) <- "Pots!!!"

bold(jams1)[1, 1:ncol(jams1)] <- FALSE
```

`r chunk_reveal(chunk_name = "the_chunk", break_type = "auto", ...)`



```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 120%}

@media print {
  .has-continuation {
    display: block;
  }
}
```

