---
title: "huxbasics"
subtitle: ""
author: ""
output:
  xaringan::moon_reader:
    seal: FALSE
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:10
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---



```{r, include = F}
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, comment = "", cache = F)
library(flipbookr)
library(tidyverse)
load("current_image.Rdata")
```


```{r, echo = F, eval = TRUE , message = F, warning = F}
xaringanExtra::use_share_again()
```


```{r the_chunk, include = F}
library(huxtable)
hux(Type  = c("Strawberry", "Raspberry", "Plum"),
    Price = c(1.90, 2.10, 1.80)) %>% 
  set_all_padding(4) %>% 
  set_outer_padding(0) %>% 
  set_number_format(2) %>% 
  set_bold(row = 1, col = everywhere) %>% 
  set_bottom_border(1, everywhere) %>% 
  set_width(0.4) %>% 
  set_caption("Pots of jam for sale")
```

`r chunk_reveal(chunk_name = "the_chunk", break_type = "auto", ...)`



```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 120%}

@media print {
  .has-continuation {
    display: block;
  }
}
```

