---
title: "huxborders"
subtitle: ""
author: ""
output:
  xaringan::moon_reader:
    seal: FALSE
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:10
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---



```{r, include = F}
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, comment = "", cache = F)
library(flipbookr)
library(tidyverse)
load("current_image.Rdata")
```


```{r, echo = F, eval = TRUE , message = F, warning = F}
xaringanExtra::use_share_again()
```


```{r the_chunk, include = F}
hux(Type  = c("Strawberry", "Raspberry", "Plum"),
    Price = c(1.90, 2.10, 1.80)) %>%
  set_all_borders(brdr(0.4, "dotted", "white")) %>%
  set_right_border(everywhere, 1, 
                   brdr(thickness = 3, 
                        style = "double", 
                        color = "grey")) %>%
  set_right_border(everywhere, 
                   1, 
                   3) %>%
  set_lr_borders(value = 
                   brdr(thickness = 8, 
                        style = "solid", 
                        color = "magenta")) %>%
  set_outer_borders(value = 
                      brdr(thickness = 2, 
                           style = "dashed", 
                           color = "green")) %>%    
  set_tb_borders(value = 
                   brdr(thickness = 1, 
                        style = "dotted", 
                        color = "goldenrod"))
```

`r chunk_reveal(chunk_name = "the_chunk", break_type = "auto", ...)`



```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 120%}

@media print {
  .has-continuation {
    display: block;
  }
}
```

