---
title: "huxformat"
subtitle: ""
author: ""
output:
  xaringan::moon_reader:
    seal: FALSE
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:10
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---



```{r, include = F}
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, comment = "", cache = F)
library(flipbookr)
library(tidyverse)
load("current_image.Rdata")
```


```{r, echo = F, eval = TRUE , message = F, warning = F}
xaringanExtra::use_share_again()
```


```{r the_chunk, include = F}
data.frame(Type  = c("Strawberry", "Raspberry", "Plum"),
    Price = c(1.90, 2.10, 1.80)) %>% 
  as_hux() %>% 
  set_text_color(row = 2:3, col = 1, 
                 value = "purple") %>% 
  set_background_color(row = evens, 
                       col = everywhere, 
                       value = "grey85") %>% 
  set_background_color(odds, everywhere, 
                       "grey93") %>% 
  set_markdown_contents(1, 1, "*Type* of jam") %>% 
  set_markdown_contents(1, 2, "*Price* of jam") %>% 
  set_markdown_contents(3, 2, "~~2.10~~ **Sale!** 1.50") %>%
  set_right_border(everywhere, 1, brdr(3, "double", "grey"))
```

`r chunk_reveal(chunk_name = "the_chunk", break_type = "auto", ...)`



```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 120%}

@media print {
  .has-continuation {
    display: block;
  }
}
```

