---
title: Long Table
subtitle: a tutorial
---


```{r, include = F}
options(knitr.duplicate.label = "allow")
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, 
                      comment = "", cache = F, echo = F, error = F)
library(flipbookr)
library(flextable)
library(tidyverse)
library(officer)
```



### What to expect: insights and products using {flipbookr} {.tabset .tabset-fade .tabset-pills}

#### {flextable}

```{r flex_long}
gapminder::gapminder %>% 
  filter(year == 2002) %>% 
  head() %>%
  select(year, continent, everything()) %>% 
  flextable() %>% 
  theme_box() %>% 
  merge_v(j = c("year", "country", "continent") ) %>% 
  set_header_labels(country = "The Country Name", 
                    year = "Year", 
                    continent = "",
                    pop = "Population") %>% 
  autofit() %>% 
  bg(bg = "grey95", part = "body") %>% 
  bg(bg = "steelblue", part = "header") %>% 
  color(color = "oldlace", part = "header") %>% 
  font(fontname = "Times") %>% 
  bg(bg = "grey70", j = 6) %>% 
  bg(bg = "goldenrod2", j = 1) %>% 
  rotate(j = 1:4, rotation="btlr", part = "header") %>% 
  rotate(j = 3, rotation="lrtb", part = "header") %>% 
  rotate(i = 3, j = 2, rotation="btlr", part = "body") %>% 
  rotate(j = 1, rotation="btlr", part = "body") %>%
  # conditional formatting
  color(i = ~ lifeExp > 75, 
        j = ~ country + lifeExp, 
        color = "goldenrod4") %>% 
  bold(j = c("year", "gdpPercap"), 
       bold = TRUE) %>% 
  align(align = "center", part = "all" ) %>% 
  fontsize(j = "continent", size = 14) %>% 
  fontsize(j = "year", size = 20) %>% 
  color(j = 1, color = "steelblue", part = "body") %>% 
  line_spacing(space = 3, part = "header") %>% 
  vline(border = fp_border(color="goldenrod3", 
                           style = "dashed"), 
        part = "all" ) %>% 
  hline_bottom(border = 
                  fp_border(color="steelblue", 
                            style = "solid", width = 5), 
               part = "body" ) %>% 
  hline(i = 5, border = fp_border(color = "plum4", width = 4)) %>% 
  hline_top(border = fp_border(color="goldenrod3", width = 3), 
            part = "all")
```

```{r, eval = F}
embed_flipbook("flex_long",
               use_share_again = T,
               use_embed_xaringan = T,
               font_size = 80)
```

#### {gt}

```{r gt_long, include=FALSE}
gapminder::gapminder %>% 
  filter(year == 2002) %>% 
  head() %>%
  select(year, continent, everything()) %>% 
  gt::gt()
```

```{r}
embed_flipbook("gt_long",
               use_share_again = T,
               use_embed_xaringan = T,
               font_size = 80)
```


#### {huxtable}

```{r hux_long, include = T}
library(huxtable)
gapminder::gapminder %>% 
  filter(year == 2002) %>% 
  head() %>%
  select(year, continent, everything()) %>% 
  hux() %>% 
  set_all_border_colors(value = "grey10") %>% 
  set_lr_borders(value =
                   brdr(thickness = 1,
                        style = "dotted",
                        color = "goldenrod")) %>% 
  set_background_color(row = everywhere,
                       col = everywhere,
                       value = "grey85") %>% 
  set_background_color(row = 1,
                       col = everywhere,
                       value = "steelblue") %>% 
  set_text_color(row = -1,
                 col = everywhere,
                 value = "black") %>% 
  set_text_color(row = -1,
                 col = everywhere,
                 value = "black") %>% 
  merge_cells(row = 2:7, col = 1) %>% 
  merge_cells(row = 4:5, col = 2) %>% 
  map_text_color(by_regex("Al" = "goldenrod4", "navy")) %>% 
  map_text_color(row = 2:7, col = 4, 
                 by_colorspace("darkred", "red", "red2", colwise = TRUE))
```


```{r, eval = T}
embed_flipbook("hux_long",
               use_share_again = T,
               use_embed_xaringan = T,
               font_size = 80)
```

