---
title: "### using tidyverse 'verbs' to create pop count by continent in 2002 with percentages and totals"
subtitle: ""
author: ""
output:
  xaringan::moon_reader:
    seal: FALSE
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:10
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---



```{r, include = F}
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, comment = "", cache = F)
library(flipbookr)
library(tidyverse)
load("current_image.Rdata")
```


```{r, echo = F, eval = FALSE , message = F, warning = F}
xaringanExtra::use_share_again()
```


```{r the_chunk, include = F}
gapminder::gapminder %>% 
  filter(year == 2002) %>% 
  group_by(continent) %>% 
  summarise(population = sum(pop)) %>% 
  mutate(percent = 100 * round(prop.table(population), 3) ) ->
base
  
base %>% 
  summarise(percent = sum(percent), 
            population = sum(population),
            continent = "Totals") ->
totals
bind_rows(base, totals) %>% 
  mutate(`Population (millions)` = population/1000000) %>% 
  mutate(percent = round(percent, 2)) %>% 
  rename(` ` = continent) %>% 
  select(` `, `Population (millions)`, percent)
```

`r chunk_reveal(chunk_name = "the_chunk", break_type = "auto", ...)`



```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 80%}

@media print {
  .has-continuation {
    display: block;
  }
}
```

