---
title: "named colors_colorful"
subtitle: ""
author: ""
output:
  xaringan::moon_reader:
    seal: FALSE
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:10
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---



```{r, include = F}
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, comment = "", cache = F)
library(flipbookr)
library(tidyverse)
load("current_image.Rdata")
```


```{r, echo = F, eval = TRUE , message = F, warning = F}
xaringanExtra::use_share_again()
```


```{r the_chunk, include = F}
library(tidyverse)

my_colors <- colors()[!str_detect(colors(), "^grey|^gray|indian|peru|navajo")]
grays <- colors()[str_detect(colors(), "^grey|^gray")]

num_columns <- 7
num_colors <- length(my_colors)
start_color <- 1
end_color <- start_color + 
  num_colors - 1
the_colors <- my_colors[start_color:end_color]


the_colors %>% 
  matrix(ncol = num_columns, byrow = F, ) %>% 
  as_tibble() %>% 
  mutate_at(.vars = 1:num_columns, 
            funs(factor(., 
                        levels = 
                          rev(the_colors), 
                        ordered = T))) %>% 
  gt::gt() %>% 
  gt::data_color(columns = 1:num_columns,
                 colors = scales::col_factor(
                   palette = the_colors,
                   domain = NULL,
                   reverse = TRUE)
                 ) %>%
  gt::tab_options(
    column_labels.hidden = TRUE
  )
```

`r chunk_reveal(chunk_name = "the_chunk", break_type = "auto", ...)`



```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 80%}

@media print {
  .has-continuation {
    display: block;
  }
}
```

