---
title: "Flipbooking"
subtitle: "With flipbookr and xaringan"
author: "Gina Reynolds, December 2019"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:10
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---



```{r, include = F}
# This is the recommended set up for flipbooks
# you might think about setting cache to TRUE as you gain practice --- building flipbooks from scratch can be time consuming
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, comment = "", cache = F, dev = "svg", fig.ext = "svg")
library(flipbookr)
library(tidyverse)
```


`r chunk_reveal("tables", break_type = "rotate")`

```{r tables, eval = F, echo = F}
gapminder::gapminder %>% 
  filter(year == 2002) %>% 
  tibble() #ROTATE
  data.frame() #ROTATE
  data.table::data.table() #ROTATE
  flextable::flextable() #ROTATE
  knitr::kable() #ROTATE
  gt::gt() #ROTATE
  DT::datatable() #ROTATE
```



---

# list column

---

`r chunk_reveal("listcolumn", break_type = "rotate")`

```{r listcolumn, eval = F, echo = F}
tibble(x = c(1,2,3,4,6),
       y = 1:5,
       z = list(1:2, 4:5, 8, NA, c(1,7,9,0))) %>% 
  tibble() #ROTATE
  data.frame() #ROTATE
  data.table::data.table() #ROTATE
  knitr::kable() #ROTATE
  gt::gt() #ROTATE
  DT::datatable() #ROTATE
```

---

# group

---

`r chunk_reveal("group", break_type = 1)`

```{r group, eval = F, echo = F}
gapminder::gapminder %>%
  group_by(country) %>% 
  filter(year > 1990) %>% 
  filter(continent == "Americas") %>% 
  select(-continent) %>% 
  gt::gt()
```

---





```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 80%}

@media print {
  .has-continuation {
    display: block;
  }
}
```
