---
title: wide
---


```{r, include = F}
options(knitr.duplicate.label = "allow")
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, 
                      comment = "", cache = F, echo = F, error = F)
library(flipbookr)
library(flextable)
library(tidyverse)
library(officer)
```


---



### A wide display w/ groups {.tabset .tabset-fade .tabset-pills}


#### {tidyverse}


```{r manipulation}
gapminder::gapminder %>% 
  filter(country %in% 
           c("Australia", "New Zealand", 
             "Canada", "United States", "Mexico"),
         year > 1990) %>% 
  mutate(gdp_billion = pop * gdpPercap/1000000000) %>% 
  mutate(gdp_billion = round(gdp_billion,1)) %>% 
  select(1:3, gdp_billion) %>% 
  pivot_wider(values_from = gdp_billion,names_from = year) %>% 
  select(continent, everything()) %>% 
  arrange(continent) %>% 
  mutate(Total = `1992` + `1997` + `2002` + `2007`) %>% 
  mutate(is_sub = F) ->
prep

prep %>% 
  group_by(continent) %>% 
  summarise_at(vars(`1992`:Total), sum, na.rm = TRUE) %>% 
  mutate(country = "Total") %>% 
  mutate(is_sub = T) %>% 
  bind_rows(prep, .) %>% 
  mutate(is_grand = F) %>% 
  bind_rows(prep %>% 
              summarise_at(vars(`1992`:Total), 
                           sum, na.rm = TRUE) %>% 
              mutate(country = "Grand Total") %>% 
              mutate(is_sub = F) %>% 
              mutate(is_grand = T)) %>% 
  arrange(is_grand, continent, is_sub) ->
arranged_table

arranged_table
```


```{r}
embed_flipbook("manipulation",
               use_share_again = T,
               use_embed_xaringan = T,
               font_size = 80)
```

#### {flextable}

```{r flex_wide_format}
arranged_table %>% 
  select(-is_sub, -is_grand) %>% 
  flextable() %>% 
  theme_box() %>% 
  merge_v() %>% 
  rotate(j = 1, part = "body", rotation = "btlr") %>% 
  set_header_labels(continent = "",
                    country = "") %>% 
  bg(bg = "aliceblue", part = "all") %>% 
  bg(i = ~ country == "Total", 
     bg = "steelblue3") %>% 
  bg(i = ~ country == "Grand Total", 
     bg = "steelblue3") %>% 
  color (i = ~ country == "Grand Total", 
     color = "grey90") %>% 
  bg(j = "continent", bg = "steelblue3") %>% 
  bold(j = "Total", part = "all") %>% 
  bold(i = ~ str_detect(country, "Total")) %>% 
  font(fontname = "Times") %>% 
  flextable::set_caption("Very good") %>% 
  flextable::add_header(continent = "This is my title") %>% 
  flextable::add_footer(country = "A footnote goes here") %>% 
  merge_h()
  
```


```{r}
embed_flipbook("flex_wide_format",
               use_share_again = T,
               use_embed_xaringan = T,
               font_size = 80)
```


#### {gt}

```{r gt_wide, include = F}
library(gt)
gapminder::gapminder %>% 
  filter(country %in% 
           c("Australia", "New Zealand", 
             "Canada", "United States", "Mexico"),
         year > 1990) %>% 
  mutate(gdp_billion = pop * gdpPercap/1000000000) %>% 
  mutate(gdp_billion = round(gdp_billion,1)) %>% 
  select(1:3, gdp_billion) %>% 
  pivot_wider(values_from = gdp_billion,names_from = year) %>% 
  select(continent, everything()) %>% 
  arrange(continent) %>% 
  group_by(continent) %>% 
  gt() %>% 
  gt::grand_summary_rows(
    columns = vars(`1992`, `1997`, `2002`, `2007`),
    fns = list(
      `grand total` = ~sum(.),
      mean = ~mean(.)),
    formatter = fmt_number,
    use_seps = FALSE
  ) %>% 
  summary_rows(
    groups = TRUE,
    columns = vars(`1992`, `1997`, `2002`, `2007`),
    fns = list(`continent total` = "sum"),
    formatter = fmt_number,
    decimals = 0,
    use_seps = TRUE
  ) %>% 
  tab_header(title = "A countries table")
```

```{r}
embed_flipbook("gt_wide",
               use_share_again = T,
               use_embed_xaringan = T,
               font_size = 80)
```

